services:
  backend:
    build:
      context: ./backend  
    ports:
      - "8000:8000" 
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  frontend:
    build:
      context: ./frontend 
    ports:
      - "3000:3000"  
    depends_on:
      - backend  
