version: '3.9'

services:
  backend:
    build: ./backend
    container_name: django_backend
    volumes:
      - ./backend:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend_dev
    volumes:
      - ./frontend:/app
      - /app/node_modules  
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true  
    depends_on:
      - backend
    restart: always


volumes:
  static_volume:
  media_volume:
